name: 'Test'

on:
  pull_request:
    branches: [main]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout code repository source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm t -- --testPathIgnorePatterns ./test/fail.test.ts
